/* Atlantis Paradise Island — interactive directory data
   Coordinates are percentages of the map layout box (2016 x 1287).
   Inventory cross-checked against the official resort map PDF
   (Atlantis Map_MonumentSign_033126) and atlantisbahamas.com, Aug 2026. */

const BOOK_STAY = 'https://secure.atlantisbahamas.com/';
const BOOK_PLAY = 'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis';

/* top-level menu */
const CATEGORIES = {
  stay:        { label: 'Stay',        color: '#254297' },
  experiences: { label: 'Experiences', color: '#2F9E77' },
  aquaventure: { label: 'Aquaventure', color: '#3AB0C8' },
  dining:      { label: 'Dining',      color: '#EB897C' }
};

/* second level, shown when Experiences is active */
const SUBCATEGORIES = {
  marine:        'Marine Activities',
  dolphin:       'Dolphin Cay',
  pools:         'Pools',
  entertainment: 'Entertainment',
  casino:        'Casino',
  spa:           'Spa & Fitness',
  golf:          'Golf & Tennis',
  shopping:      'Shopping'
};

const PLACES = [
  /* ------------------------------------------------------------- STAY */
  { id:'royal', cat:'stay',
    name:'The Royal', kicker:'The beacon of Atlantis',
    x:53.5, y:24.0, zoom:2.02,
    image:'assets/img/royal.jpg?v=24',
    blurb:'The hotel that made Atlantis a landmark. Twin coral-pink towers joined by the Bridge Suite, with the Great Hall of Waters and the Ruins Lagoon at their feet.',
    points:['Great Hall of Waters looks straight into the Ruins Lagoon',
            'Walk-out access to Aquaventure, the Casino and Mandara Spa',
            "Home of the Bridge Suite, the resort's most famous room"],
    learn:'https://www.atlantisbahamas.com/rooms/royaltowers', book:BOOK_STAY },
  { id:'cove', cat:'stay',
    name:'The Cove', kicker:'All-suite, ocean-facing luxury',
    x:79.0, y:14.6, zoom:2.11,
    image:'assets/img/cove.jpg?v=24',
    blurb:'Immaculately designed to provide guests with luxury, sensuality and white-glove Bahamian service. Every room is a suite.',
    points:['Private access to Paradise Beach and Cove Beach',
            'The Cove Pool — adults-only beach club with poolside gaming',
            'Suite-only tower with dedicated Cove guest services'],
    learn:'https://www.atlantisbahamas.com/rooms/thecoveatlantis', book:BOOK_STAY },
  { id:'reef', cat:'stay',
    name:'The Reef', kicker:'Residences with kitchens',
    x:71.9, y:7.0, zoom:2.11,
    image:'assets/img/reef.jpg?v=24',
    blurb:'For those who want the comforts of home with remarkable views of a tropical paradise. Studio-to-multi-bedroom residences with full kitchens and balconies.',
    points:['Full kitchens and laundry — built for longer stays',
            'Shares Paradise Beach and the Cascades Pool with The Cove',
            'Closest tower to Dolphin Cay and the Tennis Center'],
    learn:'https://www.atlantisbahamas.com/rooms/thereefatlantis/accommodations', book:BOOK_STAY },
  { id:'coral', cat:'stay',
    name:'The Coral', kicker:'Fresh design, marina views',
    x:39.2, y:60.6, zoom:1.94,
    image:'assets/img/coral.jpg?v=24',
    blurb:'Newly reimagined and set between the marina and the sea, The Coral pairs a bright contemporary aesthetic with views of some of the most beautiful yachts in the world.',
    points:['The Coral Pool and a private stretch of Atlantis Beach',
            'Two minutes on foot to Marina Village and the Casino',
            'The best-value gateway to everything Atlantis includes'],
    learn:'https://www.atlantisbahamas.com/rooms/coraltowers', book:BOOK_STAY },
  { id:'harborside', cat:'stay',
    name:'Harborside Resort', kicker:'Villas on the harbour',
    x:16.2, y:29.4, zoom:2.02,
    image:'assets/img/harborside.jpg?v=24',
    blurb:'A nautical oasis of low-rise villas across the water from the marina, with full kitchens, its own pools and a slower rhythm.',
    points:['Villa-style units with full kitchens and living rooms',
            'Two dedicated pools and a poolside bar away from the crowds',
            'Nassau Harbour views; short walk to Marina Village'],
    learn:'https://www.atlantisbahamas.com/rooms/harborsideresort', book:BOOK_STAY },

  /* ------------------------------------------------- AQUAVENTURE (core) */
  { id:'aquaventure', cat:'aquaventure',
    name:'Aquaventure', kicker:'141 acres of water',
    x:74.6, y:28.4, zoom:1.67,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:'The waterscape at the centre of the resort: 141 acres holding 20 million gallons of water, more than 20 swimming areas, high-speed slides and a mile-long river ride.',
    points:['20 million gallons across more than 20 swimming areas',
            'Included with every Atlantis room — no extra ticket',
            "Poseidon's Playzone water fort for younger kids"],
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:BOOK_PLAY },
  { id:'power-tower', cat:'aquaventure',
    name:'Power Tower', kicker:'The Abyss · The Drop · The Surge · The Falls',
    x:80.9, y:31.5, zoom:2.29,
    image:'assets/img/power-tower.jpg?v=24',
    blurb:'A 120-foot tower stacking four of the resort\u2019s fastest rides. The Surge sends inner tubes over a camel-back drop into white water.',
    points:['120 feet tall — the highest launch point at Aquaventure',
            'The Surge: camel-back drop into a white-water run',
            '48" minimum height on the tower rides'],
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:BOOK_PLAY },
  { id:'mayan-temple', cat:'aquaventure',
    name:'Mayan Temple', kicker:'Leap of Faith',
    x:71.3, y:38.0, zoom:2.29,
    image:'assets/img/mayan-temple.jpg?v=24',
    blurb:'The most photographed drop in the Caribbean. Leap of Faith is a 60-foot near-vertical body slide that fires you through a clear acrylic tunnel running the length of a shark-filled lagoon.',
    points:['Leap of Faith — a 60-foot, almost-vertical drop',
            'Clear tunnel through a live marine lagoon',
            'Challenger Slides race side by side with speed clocks'],
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:BOOK_PLAY },
  { id:'rapids-river', cat:'aquaventure',
    name:'The Rapids River', kicker:'A mile of moving water',
    x:70.6, y:22.6, zoom:1.94,
    image:'assets/img/rapids-river.jpg?v=24',
    blurb:'Not a lazy river. A mile-long circuit with wave surges, elevation changes and drops of up to seven feet.',
    points:['One mile long with wave surges and white water',
            'Drops of up to seven feet along the route',
            'Rejoins the calmer Lazy River Ride for an easier lap'],
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:BOOK_PLAY },

  /* ----------------------------------------- EXPERIENCES (headline set) */
  { id:'the-dig', cat:'experiences', sub:'marine',
    name:'The Dig', kicker:'The Lost City, below sea level',
    x:49.2, y:37.2, zoom:2.2,
    image:'assets/img/the-dig.jpg?v=24',
    blurb:'A walk through the excavated ruins of the Lost City of Atlantis, where exotic marine species have taken up residence inside the streets and laboratories of a civilisation that supposedly sank 11,000 years ago.',
    points:['Set beneath The Royal, open to all resort guests',
            'Part of the largest open-air marine habitat in the world',
            'Over 250 marine species across 14 connected lagoons'],
    learn:'https://www.atlantisbahamas.com/things-to-do/marine-habitat', book:BOOK_PLAY },
  { id:'predator-lagoon', cat:'experiences', sub:'marine',
    name:'Predator Lagoon', kicker:'A 100-foot tunnel through the sharks',
    x:57.5, y:59.9, zoom:2.2,
    image:'assets/img/predator-lagoon.jpg?v=24',
    blurb:'A clear underwater tunnel runs 100 feet through the lagoon, giving 360-degree views of sharks, barracuda, rays, sawfish and giant grouper.',
    points:['100-foot transparent tunnel with 360\u00b0 views',
            'Sharks, barracuda, rays and critically endangered sawfish',
            'Feedings Tuesday–Sunday at 8am and 3pm'],
    learn:'https://www.atlantisbahamas.com/things-to-do/marine-habitat', book:BOOK_PLAY },
  { id:'dolphin-cay', cat:'experiences', sub:'dolphin',
    name:'Dolphin Cay', kicker:'14 acres · rescue and rehabilitation',
    x:55.2, y:15.1, zoom:2.11,
    image:'assets/img/dolphin-cay.jpg?v=24',
    blurb:"One of the most sophisticated marine habitats in the world, and the Caribbean's premier marine life rescue and rehabilitation facility.",
    points:['Playtime with Dolphins, Swim in Wonder, Sea Lion Interaction',
            'Ultimate Trainer for a Day — work beside an animal behaviorist',
            'Every programme supports the Atlantis Blue Project Foundation'],
    learn:'https://www.atlantisbahamas.com/things-to-do/dolphin-cay', book:BOOK_PLAY },
  { id:'cove-beach', cat:'experiences', sub:'pools',
    name:'Cove Beach', kicker:'The quiet crescent',
    x:87.0, y:25.5, zoom:1.94,
    image:'assets/img/cove-beach.jpg?v=24',
    blurb:'A soft white crescent on the Atlantic side of the resort, backed by The Cove and its adults-only pool.',
    points:['Beaches open 10am–7pm, seasonally adjusted',
            'Private cabanas available along the sand',
            'Paradise Beach next door is reserved for Cove and Reef guests'],
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:BOOK_PLAY },
  { id:'paradise-lagoon', cat:'experiences', sub:'pools',
    name:'Paradise Lagoon', kicker:'Seven acres of protected water',
    x:49.6, y:51.2, zoom:1.85,
    image:'assets/img/paradise-lagoon.jpg?v=24',
    blurb:'A seven-acre saltwater lagoon in the heart of the property with beaches on both shores.',
    points:['Paddleboards, kayaks, water bikes and snorkel gear at the south beach',
            'North beach has a gradual entry — best for small children',
            'Book gear through the Blue Adventures desk'],
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:BOOK_PLAY },
  { id:'casino', cat:'experiences', sub:'casino',
    name:'The Casino', kicker:'Built over a seven-acre lagoon',
    x:39.4, y:47.2, zoom:2.11,
    image:'assets/img/casino.jpg?v=24',
    blurb:'A gaming floor suspended over a seven-acre lagoon, under soaring ceilings, Atlantean sculpture and the Chihuly glass of the Temple of the Sun.',
    points:['80 gaming tables — blackjack, craps, roulette, baccarat',
            'Slots 24/7; table games 10am–4am daily',
            'Cleitos private tables and the Sea Glass lounge'],
    learn:'https://www.atlantisbahamas.com/casino', book:BOOK_PLAY },
  { id:'mandara-spa', cat:'experiences', sub:'spa',
    name:'Mandara Spa', kicker:'Balinese healing, Bahamian setting',
    x:61.4, y:23.0, zoom:2.2,
    image:'assets/img/mandara-spa.jpg?v=24',
    blurb:'Ancient Balinese healing and traditional European therapy blended with natural elements unique to The Bahamas.',
    points:['Open daily 10am–6pm',
            'Currently at the Mandara Boutique Spa, Royal Tower West',
            'A fully reimagined flagship spa debuts Summer 2026'],
    learn:'https://www.atlantisbahamas.com/things-to-do/spa', book:BOOK_PLAY },
  { id:'marina-village', cat:'experiences', sub:'shopping',
    name:'Marina Village', kicker:'65,000 sq ft of shops and tables',
    x:7.4, y:57.6, zoom:2.02,
    image:'assets/img/marina-village.jpg?v=24',
    blurb:'An open-air Bahamian marketplace on the water — 65,000 square feet, more than 20 designer and retail shops, and everything from conch shacks to Nobu.',
    points:['Over 20 designer and retail shops, open 10am–10pm',
            'Straw Market across the way — around 60 Bahamian craft booths',
            'Food Truck Village by Tin Ferl for casual Bahamian plates'],
    learn:'https://www.atlantisbahamas.com/things-to-do/marina-village', book:BOOK_PLAY },
  { id:'atlantis-marina', cat:'experiences', sub:'shopping',
    name:'Atlantis Marina', kicker:'Deep-water berths for megayachts',
    x:26.0, y:45.4, zoom:2.11,
    image:'assets/img/atlantis-marina.jpg?v=24',
    blurb:'The protected deep-water marina that gives the resort its front row of megayachts, wrapped by Marina Village and its restaurants.',
    points:['Full-service marina at the centre of the resort',
            'Departure point for fishing charters and boat excursions',
            'Ringed by Marina Village dining and shopping'],
    learn:'https://www.atlantisbahamas.com/things-to-do/marina-village', book:BOOK_PLAY },
  { id:'theatre', cat:'experiences', sub:'entertainment',
    name:'Atlantis Theatre', kicker:'Atlantis LIVE concert series',
    x:30.9, y:73.4, zoom:2.11,
    image:'assets/img/theatre.jpg?v=24',
    blurb:"The resort's stage for the Atlantis LIVE concert series, with the Box Office alongside the Convention Center.",
    points:['Atlantis LIVE brings touring acts to the resort theatre',
            'Box Office shared with the Convention Center',
            'Aura and Bar Sol carry the night on after the show'],
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:BOOK_PLAY },
  { id:'kids', cat:'experiences', sub:'entertainment',
    name:'Atlantis Kids Adventures', kicker:'Ages 3–12',
    x:52.9, y:27.9, zoom:2.2,
    image:'assets/img/kids.jpg?v=24',
    blurb:'A club where children choose their own adventure across themed rooms — a Victorian dollhouse and Lego build room for the little ones, a culinary studio and gaming den for the older group.',
    points:['Themed rooms split by age: 3–6 and 7–12',
            'Morning, afternoon and late-night sessions',
            'Reservation and payment required to hold a spot'],
    learn:'https://www.atlantisbahamas.com/atlantis-kids-adventures', book:BOOK_PLAY },
  { id:'golf', cat:'experiences', sub:'golf',
    name:'Ocean Club Golf Course', kicker:'Tom Weiskopf · par 72',
    x:3.2, y:65.8, zoom:1.94, offmap:true,
    image:'assets/img/golf.jpg?v=24',
    blurb:'Just west of the resort, a Tom Weiskopf championship layout running more than 7,100 yards along the tip of the Paradise Island peninsula.',
    points:['Par 72, over 7,100 yards, ocean on both sides',
            'Crosswinds off the Atlantic make it play longer than the card',
            'Lessons, clinics, Callaway rentals and Play with a Pro'],
    learn:'https://www.atlantisbahamas.com/things-to-do/golf', book:BOOK_PLAY },

  /* ---------------------------------------------------------- DINING */
  { id:'nobu', cat:'dining',
    name:"Nobu", kicker:"Marina \u00b7 Japanese",
    x:34.7, y:43.1, zoom:2.2,
    image:'assets/img/atlantis-marina.jpg?v=24',
    blurb:"Nobu Matsuhisa's Bahamian outpost, off the Royal's casino level above the marina.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'olives', cat:'dining',
    name:"Todd English's Olives", kicker:"Marina \u00b7 Mediterranean",
    x:32.2, y:47.2, zoom:2.2,
    image:'assets/img/atlantis-marina.jpg?v=24',
    blurb:"Mediterranean plates from Todd English, overlooking the marina.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'platos', cat:'dining',
    name:"Plato's", kicker:"The Royal \u00b7 Lounge",
    x:43.4, y:37.1, zoom:2.2,
    image:'assets/img/royal.jpg?v=24',
    blurb:"A lounge and light-bites spot inside The Royal.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'poseidons-table', cat:'dining',
    name:"Poseidon's Table", kicker:"The Royal \u00b7 Buffet",
    x:45.0, y:34.4, zoom:2.2,
    image:'assets/img/royal.jpg?v=24',
    blurb:"The Royal's buffet restaurant, open for breakfast and dinner.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'sea-glass', cat:'dining',
    name:"Sea Glass", kicker:"The Cove \u00b7 Bar & gaming",
    x:73.5, y:12.8, zoom:2.2,
    image:'assets/img/cove.jpg?v=24',
    blurb:"An intimate lounge at The Cove with slots, electronic roulette and blackjack.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'starbucks-reef', cat:'dining',
    name:"Starbucks at The Reef", kicker:"The Reef \u00b7 Coffee",
    x:69.9, y:7.9, zoom:2.2,
    image:'assets/img/reef.jpg?v=24',
    blurb:"Coffee counter in The Reef lobby.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'sun-ice', cat:'dining',
    name:"Sun & Ice", kicker:"The Coral \u00b7 Gelato",
    x:38.3, y:57.2, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Gelato and cold treats by The Coral lobby.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'tlv-kitchen', cat:'dining',
    name:"TLV Kitchen", kicker:"The Beach \u00b7 Mediterranean",
    x:33.7, y:83.6, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Eastern Mediterranean cooking near The Beach tower.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'virgils', cat:'dining',
    name:"Virgil's Real BBQ", kicker:"The Coral \u00b7 Barbecue",
    x:40.1, y:56.6, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Pit barbecue and Southern sides at The Coral.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'voyagers', cat:'dining',
    name:"Voyager's", kicker:"The Beach \u00b7 All-day",
    x:32.3, y:83.2, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Casual all-day dining near the Conference Center.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'bahamian-club', cat:'dining',
    name:"Bahamian Club", kicker:"The Coral \u00b7 Steakhouse",
    x:29.6, y:71.8, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"A classic chophouse serving steaks and seafood.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'casa-dangelo', cat:'dining',
    name:"Casa D'Angelo", kicker:"The Coral \u00b7 Italian",
    x:30.6, y:71.1, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Northern Italian cooking from chef Angelo Elia.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'chop-stix', cat:'dining',
    name:"Chop Stix", kicker:"The Coral \u00b7 Chinese",
    x:29.7, y:70.2, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Cantonese and Szechuan dishes at The Coral.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'fish-jose-andres', cat:'dining',
    name:"Fish by Jos\u00e9 Andr\u00e9s", kicker:"The Cove \u00b7 Seafood",
    x:71.3, y:12.0, zoom:2.2,
    image:'assets/img/cove.jpg?v=24',
    blurb:"Jos\u00e9 Andr\u00e9s' seafood restaurant at The Cove.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'moon-bar', cat:'dining',
    name:"Moon Bar", kicker:"Casino \u00b7 Cocktails",
    x:33.5, y:46.2, zoom:2.2,
    image:'assets/img/casino.jpg?v=24',
    blurb:"A cocktail bar suspended over the casino floor.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'mosaic', cat:'dining',
    name:"Mosaic", kicker:"The Cove \u00b7 Marketplace",
    x:71.9, y:15.6, zoom:2.2,
    image:'assets/img/cove.jpg?v=24',
    blurb:"A market-style restaurant with open kitchens at The Cove.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'murrays', cat:'dining',
    name:"Murray's Delicatessen", kicker:"Marina \u00b7 Deli",
    x:28.4, y:54.4, zoom:2.2,
    image:'assets/img/marina-village.jpg?v=24',
    blurb:"New York-style deli counter by the marina.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'marina-pizzeria', cat:'dining',
    name:"Marina Pizzeria", kicker:"Marina \u00b7 Pizza",
    x:27.0, y:55.7, zoom:2.2,
    image:'assets/img/marina-village.jpg?v=24',
    blurb:"Wood-fired pizza on the marina walk.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'marina-village-dining', cat:'dining',
    name:"Marina Village Dining", kicker:"Marina Village \u00b7 Waterfront",
    x:8.6, y:56.7, zoom:2.2,
    image:'assets/img/marina-village.jpg?v=24',
    blurb:"The waterfront cluster of Marina Village restaurants, from conch shacks to steakhouses.",
    learn:'https://www.atlantisbahamas.com/things-to-do/marina-village', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'beach-bar', cat:'dining',
    name:"Beach Bar", kicker:"Atlantis Beach \u00b7 Bar",
    x:53.3, y:85.1, zoom:2.2,
    image:'assets/img/cove-beach.jpg?v=24',
    blurb:"Beachside bar service on Atlantis Beach.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'beach-bites', cat:'dining',
    name:"Beach Bites", kicker:"Cove Beach \u00b7 Casual",
    x:83.2, y:21.2, zoom:2.2,
    image:'assets/img/cove-beach.jpg?v=24',
    blurb:"Quick bites and drinks on Cove Beach.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'breakwaters', cat:'dining',
    name:"Breakwater's Bar & Grill", kicker:"Aquaventure \u00b7 Grill",
    x:82.7, y:27.6, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"Poolside grill on the Aquaventure side of the resort.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'cascades-grill', cat:'dining',
    name:"Cascades Grill", kicker:"The Reef \u00b7 Poolside",
    x:79.8, y:4.9, zoom:2.2,
    image:'assets/img/reef.jpg?v=24',
    blurb:"Poolside grill at the Cascades Pool.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'coral-pool-cart', cat:'dining',
    name:"The Coral Pool Cart", kicker:"The Coral \u00b7 Poolside",
    x:53.4, y:63.0, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"Drinks and snacks cart at The Coral Pool.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'dive-in', cat:'dining',
    name:"Dive In", kicker:"Royal Baths \u00b7 Poolside",
    x:56.1, y:40.0, zoom:2.2,
    image:'assets/img/royal.jpg?v=24',
    blurb:"Poolside service at the Royal Baths.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'lagoon-bar', cat:'dining',
    name:"Lagoon Bar & Grill", kicker:"Paradise Lagoon \u00b7 Grill",
    x:53.4, y:54.4, zoom:2.2,
    image:'assets/img/paradise-lagoon.jpg?v=24',
    blurb:"Grill and bar on the Paradise Lagoon shore.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'mayan-hut', cat:'dining',
    name:"Mayan Hut", kicker:"Aquaventure \u00b7 Snacks",
    x:66.4, y:41.1, zoom:2.2,
    image:'assets/img/mayan-temple.jpg?v=24',
    blurb:"Snack hut beside the Mayan Temple pool.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'pisces', cat:'dining',
    name:"Pisces", kicker:"Paradise Lagoon \u00b7 Seafood",
    x:67.0, y:52.8, zoom:2.2,
    image:'assets/img/paradise-lagoon.jpg?v=24',
    blurb:"Seafood dining looking over Paradise Lagoon.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'riverbend', cat:'dining',
    name:"Riverbend Caf\u00e9", kicker:"Aquaventure \u00b7 Caf\u00e9",
    x:68.2, y:24.6, zoom:2.2,
    image:'assets/img/rapids-river.jpg?v=24',
    blurb:"Caf\u00e9 on the bend of the Rapids River.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'shark-bites', cat:'dining',
    name:"Shark Bites Bar & Grill", kicker:"Aquaventure \u00b7 Grill",
    x:69.1, y:42.7, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"Bar and grill by the Mayan Temple, with an express counter alongside.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'sip-sip', cat:'dining',
    name:"Sip Sip", kicker:"Cove Beach \u00b7 Bahamian",
    x:86.5, y:15.0, zoom:2.2,
    image:'assets/img/cove-beach.jpg?v=24',
    blurb:"Julie Lightbourn's Bahamian cooking above Cove Beach.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'splashers-snacks', cat:'dining',
    name:"Splashers Snacks", kicker:"Aquaventure \u00b7 Snacks",
    x:71.6, y:29.4, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"Snack counter at the Splashers kids' pool.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'starbucks-mayan', cat:'dining',
    name:"Starbucks at Mayan Temple", kicker:"Aquaventure \u00b7 Coffee",
    x:67.2, y:41.9, zoom:2.2,
    image:'assets/img/mayan-temple.jpg?v=24',
    blurb:"Coffee at the foot of the Mayan Temple.",
    learn:'https://www.atlantisbahamas.com/dining/dining-reservations', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },

  /* ----------------------------------------------------- AQUAVENTURE */
  { id:'grotto-pool', cat:'aquaventure',
    name:"Grotto Pool", kicker:"Aquaventure \u00b7 Pool",
    x:78.0, y:37.8, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"A cascading grotto pool tucked into the rocks with preferred seating.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'baths-colonnade', cat:'aquaventure',
    name:"Baths Colonnade Pool", kicker:"Aquaventure \u00b7 Pool",
    x:78.9, y:24.6, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"Colonnaded pool between the towers and Cove Beach.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'mayan-temple-pool', cat:'aquaventure',
    name:"Mayan Temple Pool", kicker:"Aquaventure \u00b7 Pool",
    x:72.3, y:39.7, zoom:2.2,
    image:'assets/img/mayan-temple.jpg?v=24',
    blurb:"Zero-entry pool at the base of the Mayan Temple.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'ripples-pool', cat:'aquaventure',
    name:"Ripples Kids Pool", kicker:"Aquaventure \u00b7 Kids",
    x:67.7, y:33.3, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"A shallow kids' pool in the middle of the waterscape.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'splashers-pool', cat:'aquaventure',
    name:"Splashers Kids Pool", kicker:"Aquaventure \u00b7 Kids",
    x:70.2, y:28.1, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"Water fort and slides scaled for younger children.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'poseidons-playzone', cat:'aquaventure',
    name:"Poseidon's Playzone", kicker:"Aquaventure \u00b7 Kids",
    x:43.0, y:74.0, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"A multi-level water fort with tipping buckets and slides.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'lazy-river', cat:'aquaventure',
    name:"Lazy River Ride", kicker:"Aquaventure \u00b7 River",
    x:41.4, y:77.7, zoom:2.2,
    image:'assets/img/rapids-river.jpg?v=24',
    blurb:"The calm counterpart to the Rapids River, drifting past The Beach.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'blue-adventures', cat:'aquaventure',
    name:"Blue Adventures Hut", kicker:"Aquaventure \u00b7 Watersports",
    x:69.9, y:39.9, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"Paddleboards, kayaks, water bikes and snorkel gear.",
    learn:'https://www.atlantisbahamas.com/things-to-do/aquaventure-water-park', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },

  /* ----------------------------------------------------- EXPERIENCES */
  { id:'royal-baths', cat:'experiences', sub:'pools',
    name:"The Royal Baths", kicker:"Pools \u00b7 The Royal",
    x:58.8, y:40.4, zoom:2.2,
    image:'assets/img/royal.jpg?v=24',
    blurb:"The Royal's signature pool, ringed by statuary and cabanas.",
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'lap-pool', cat:'experiences', sub:'pools',
    name:"The Lap Pool", kicker:"Pools \u00b7 The Royal",
    x:60.8, y:20.5, zoom:2.2,
    image:'assets/img/royal.jpg?v=24',
    blurb:"A quiet lap pool for swimming lengths.",
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'coral-pool', cat:'experiences', sub:'pools',
    name:"The Coral Pool", kicker:"Pools \u00b7 The Coral",
    x:50.2, y:61.3, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"The Coral's main pool with a swim-up bar.",
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'cascades-pool', cat:'experiences', sub:'pools',
    name:"Cascades Pool", kicker:"Pools \u00b7 Cove & Reef",
    x:78.9, y:4.9, zoom:2.2,
    image:'assets/img/reef.jpg?v=24',
    blurb:"Terraced pool reserved for Cove and Reef guests.",
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'cove-pool', cat:'experiences', sub:'pools',
    name:"The Cove Pool", kicker:"Pools \u00b7 Adults only",
    x:86.3, y:17.0, zoom:2.2,
    image:'assets/img/cove.jpg?v=24',
    blurb:"Adults-only beach club pool with outdoor gaming for guests 21+.",
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'river-pool', cat:'experiences', sub:'pools',
    name:"River Pool", kicker:"Pools \u00b7 The Beach",
    x:43.8, y:83.8, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"A winding pool threading the gardens behind The Beach.",
    learn:'https://www.atlantisbahamas.com/thingstodo/pools-beaches', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'aura', cat:'experiences', sub:'entertainment',
    name:"Aura Nightclub", kicker:"Entertainment \u00b7 Nightlife",
    x:34.8, y:41.3, zoom:2.2,
    image:'assets/img/theatre.jpg?v=24',
    blurb:"The resort's nightclub, above the casino floor.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'dragons', cat:'experiences', sub:'entertainment',
    name:"Dragons Ultra-Lounge", kicker:"Entertainment \u00b7 Nightlife",
    x:40.4, y:49.9, zoom:2.2,
    image:'assets/img/theatre.jpg?v=24',
    blurb:"A late-night ultra-lounge off the casino.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'crush', cat:'experiences', sub:'entertainment',
    name:"CRUSH Teen Club", kicker:"Entertainment \u00b7 Teens",
    x:35.2, y:53.8, zoom:2.2,
    image:'assets/img/kids.jpg?v=24',
    blurb:"A supervised night spot for teenagers.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'gamers-reef', cat:'experiences', sub:'entertainment',
    name:"Gamer's Reef", kicker:"Entertainment \u00b7 Arcade",
    x:53.6, y:27.9, zoom:2.2,
    image:'assets/img/kids.jpg?v=24',
    blurb:"Arcade and gaming lounge beside Atlantis Kids Adventures.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'atlantis-pals', cat:'experiences', sub:'entertainment',
    name:"Atlantis Pals", kicker:"Entertainment \u00b7 Kids",
    x:30.9, y:82.0, zoom:2.2,
    image:'assets/img/kids.jpg?v=24',
    blurb:"Character meet-and-greets and activities for younger children.",
    learn:'https://www.atlantisbahamas.com/atlantis-kids-adventures', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'atlantis-library', cat:'experiences', sub:'entertainment',
    name:"Atlantis Library", kicker:"Entertainment \u00b7 Quiet",
    x:46.7, y:66.0, zoom:2.2,
    image:'assets/img/coral.jpg?v=24',
    blurb:"A quiet reading room away from the waterpark.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'climbers-rush', cat:'experiences', sub:'entertainment',
    name:"Climber's Rush", kicker:"Entertainment \u00b7 Activity",
    x:62.3, y:23.7, zoom:2.2,
    image:'assets/img/aquaventure.jpg?v=24',
    blurb:"A climbing wall near the Mandara Spa terrace.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'pottery-studio', cat:'experiences', sub:'entertainment',
    name:"Earth & Fire Pottery Studio", kicker:"Entertainment \u00b7 Activity",
    x:34.6, y:83.6, zoom:2.2,
    image:'assets/img/kids.jpg?v=24',
    blurb:"Paint-your-own pottery studio near The Beach.",
    learn:'https://www.atlantisbahamas.com/things-to-do/entertainment', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'race-sports-book', cat:'experiences', sub:'casino',
    name:"Atlantis Race & Sports Book", kicker:"Casino \u00b7 Sports betting",
    x:35.7, y:41.3, zoom:2.2,
    image:'assets/img/casino.jpg?v=24',
    blurb:"Self-service kiosks and screens, open around the clock.",
    learn:'https://www.atlantisbahamas.com/casino', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'fitness-center', cat:'experiences', sub:'spa',
    name:"Fitness Center", kicker:"Spa & Fitness",
    x:59.7, y:22.2, zoom:2.2,
    image:'assets/img/mandara-spa.jpg?v=24',
    blurb:"Cardio and weight floor beside the Mandara Spa.",
    learn:'https://www.atlantisbahamas.com/things-to-do/spa', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'crystal-court', cat:'experiences', sub:'shopping',
    name:"Crystal Court Shoppes", kicker:"Shopping \u00b7 The Royal",
    x:29.1, y:57.7, zoom:2.2,
    image:'assets/img/marina-village.jpg?v=24',
    blurb:"The resort's luxury retail arcade.",
    learn:'https://www.atlantisbahamas.com/luxury-and-retail-shopping', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'marina-village-shops', cat:'experiences', sub:'shopping',
    name:"Marina Village Shops", kicker:"Shopping \u00b7 Marina Village",
    x:9.5, y:57.6, zoom:2.2,
    image:'assets/img/marina-village.jpg?v=24',
    blurb:"Over 20 designer and retail shops on the waterfront.",
    learn:'https://www.atlantisbahamas.com/things-to-do/marina-village', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'royal-shops', cat:'experiences', sub:'shopping',
    name:"The Royal Shops", kicker:"Shopping \u00b7 The Royal",
    x:39.4, y:40.1, zoom:2.2,
    image:'assets/img/royal.jpg?v=24',
    blurb:"Retail corridor running through The Royal.",
    learn:'https://www.atlantisbahamas.com/luxury-and-retail-shopping', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'escape-cove', cat:'experiences', sub:'shopping',
    name:"Escape at The Cove", kicker:"Shopping \u00b7 The Cove",
    x:73.8, y:14.8, zoom:2.2,
    image:'assets/img/cove.jpg?v=24',
    blurb:"Resortwear and sundries at The Cove.",
    learn:'https://www.atlantisbahamas.com/luxury-and-retail-shopping', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
  { id:'dolphin-gifts', cat:'experiences', sub:'dolphin',
    name:"Dolphin Cay Gifts & Photos", kicker:"Dolphin Cay \u00b7 Shop",
    x:59.7, y:15.2, zoom:2.2,
    image:'assets/img/dolphin-cay.jpg?v=24',
    blurb:"Photos and gifts from your Dolphin Cay programme.",
    learn:'https://www.atlantisbahamas.com/things-to-do/dolphin-cay', book:'https://www.atlantisbahamas.com/already-booked-things-to-do-atlantis' },
];
